package com.fdu.mockinterview.entity;

public class Interview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.user_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.cv_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private Integer cvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.ai_score
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String aiScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.ai_result
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String aiResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.report
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String report;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.company_name
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.position
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.create_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.update_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    private String updateDate;


    private String reportDirectory;

    public String getReportDirectory() {
        return reportDirectory;
    }

    public void setReportDirectory(String reportDirectory) {
        this.reportDirectory = reportDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.id
     *
     * @return the value of interview.id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.id
     *
     * @param id the value for interview.id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.user_id
     *
     * @return the value of interview.user_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.user_id
     *
     * @param userId the value for interview.user_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.cv_id
     *
     * @return the value of interview.cv_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public Integer getCvId() {
        return cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.cv_id
     *
     * @param cvId the value for interview.cv_id
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setCvId(Integer cvId) {
        this.cvId = cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.ai_score
     *
     * @return the value of interview.ai_score
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getAiScore() {
        return aiScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.ai_score
     *
     * @param aiScore the value for interview.ai_score
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setAiScore(String aiScore) {
        this.aiScore = aiScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.ai_result
     *
     * @return the value of interview.ai_result
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getAiResult() {
        return aiResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.ai_result
     *
     * @param aiResult the value for interview.ai_result
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setAiResult(String aiResult) {
        this.aiResult = aiResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.report
     *
     * @return the value of interview.report
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.report
     *
     * @param report the value for interview.report
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setReport(String report) {
        this.report = report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.company_name
     *
     * @return the value of interview.company_name
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.company_name
     *
     * @param companyName the value for interview.company_name
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.position
     *
     * @return the value of interview.position
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.position
     *
     * @param position the value for interview.position
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.create_date
     *
     * @return the value of interview.create_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.create_date
     *
     * @param createDate the value for interview.create_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.update_date
     *
     * @return the value of interview.update_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.update_date
     *
     * @param updateDate the value for interview.update_date
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }
}