package com.fdu.mockinterview.entity;

public class ResumeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_type.id
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_type.cv_type_text
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    private String cvTypeText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_type.create_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_type.update_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_type.id
     *
     * @return the value of resume_type.id
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_type.id
     *
     * @param id the value for resume_type.id
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_type.cv_type_text
     *
     * @return the value of resume_type.cv_type_text
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public String getCvTypeText() {
        return cvTypeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_type.cv_type_text
     *
     * @param cvTypeText the value for resume_type.cv_type_text
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public void setCvTypeText(String cvTypeText) {
        this.cvTypeText = cvTypeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_type.create_date
     *
     * @return the value of resume_type.create_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_type.create_date
     *
     * @param createDate the value for resume_type.create_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_type.update_date
     *
     * @return the value of resume_type.update_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_type.update_date
     *
     * @param updateDate the value for resume_type.update_date
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }
}