package com.fdu.mockinterview.entity;

public class Resume {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.user_id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.cv_name
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private String cvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.cv_type
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private Integer cvType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.cv_directory
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private String cvDirectory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.cv_context
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private String cvContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.create_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.update_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    private String updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.id
     *
     * @return the value of resume.id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.id
     *
     * @param id the value for resume.id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.user_id
     *
     * @return the value of resume.user_id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.user_id
     *
     * @param userId the value for resume.user_id
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.cv_name
     *
     * @return the value of resume.cv_name
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public String getCvName() {
        return cvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.cv_name
     *
     * @param cvName the value for resume.cv_name
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setCvName(String cvName) {
        this.cvName = cvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.cv_type
     *
     * @return the value of resume.cv_type
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public Integer getCvType() {
        return cvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.cv_type
     *
     * @param cvType the value for resume.cv_type
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setCvType(Integer cvType) {
        this.cvType = cvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.cv_directory
     *
     * @return the value of resume.cv_directory
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public String getCvDirectory() {
        return cvDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.cv_directory
     *
     * @param cvDirectory the value for resume.cv_directory
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setCvDirectory(String cvDirectory) {
        this.cvDirectory = cvDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.cv_context
     *
     * @return the value of resume.cv_context
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public String getCvContext() {
        return cvContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.cv_context
     *
     * @param cvContext the value for resume.cv_context
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setCvContext(String cvContext) {
        this.cvContext = cvContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.create_date
     *
     * @return the value of resume.create_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.create_date
     *
     * @param createDate the value for resume.create_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.update_date
     *
     * @return the value of resume.update_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.update_date
     *
     * @param updateDate the value for resume.update_date
     *
     * @mbg.generated Sat Jun 08 12:45:10 PDT 2024
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }
}