package com.fdu.mockinterview.mapper;

import com.fdu.mockinterview.entity.Interview;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface InterviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    @Delete({
        "delete from interview",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    @Insert({
        "insert into interview (user_id, ",
        "cv_id, ai_score, ai_result, ",
        "report, company_name, ",
        "position) ",
        "values (#{userId,jdbcType=INTEGER}, ",
        "#{cvId,jdbcType=INTEGER}, #{aiScore,jdbcType=VARCHAR}, #{aiResult,jdbcType=VARCHAR}, ",
        "#{report,jdbcType=VARCHAR}, #{companyName,jdbcType=VARCHAR}, ",
        "#{position,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insert(Interview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    @Select({
        "select",
        "id, user_id, cv_id, ai_score, ai_result, report, company_name, position, create_date, ",
        "update_date",
        "from interview",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="cv_id", property="cvId", jdbcType=JdbcType.INTEGER),
        @Result(column="ai_score", property="aiScore", jdbcType=JdbcType.VARCHAR),
        @Result(column="ai_result", property="aiResult", jdbcType=JdbcType.VARCHAR),
        @Result(column="report", property="report", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_name", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    Interview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    @Select({
        "select",
        "id, user_id, cv_id, ai_score, ai_result, report, company_name, position, create_date, ",
        "update_date",
        "from interview"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="cv_id", property="cvId", jdbcType=JdbcType.INTEGER),
        @Result(column="ai_score", property="aiScore", jdbcType=JdbcType.VARCHAR),
        @Result(column="ai_result", property="aiResult", jdbcType=JdbcType.VARCHAR),
        @Result(column="report", property="report", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_name", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    List<Interview> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Sat Jun 08 14:06:23 PDT 2024
     */
    @Update({
        "update interview",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "cv_id = #{cvId,jdbcType=INTEGER},",
          "ai_score = #{aiScore,jdbcType=VARCHAR},",
          "ai_result = #{aiResult,jdbcType=VARCHAR},",
          "report = #{report,jdbcType=VARCHAR},",
          "company_name = #{companyName,jdbcType=VARCHAR},",
          "position = #{position,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Interview record);
}