package com.fdu.mockinterview.mapper;

import com.fdu.mockinterview.entity.ResumeType;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface ResumeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_type
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    @Delete({
        "delete from resume_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_type
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    @Insert({
        "insert into resume_type (cv_type_text )",
        "values (#{cvTypeText,jdbcType=VARCHAR}) "
    })
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insert(ResumeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_type
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    @Select({
        "select",
        "id, cv_type_text, create_date, update_date",
        "from resume_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cv_type_text", property="cvTypeText", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    ResumeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_type
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    @Select({
        "select",
        "id, cv_type_text, create_date, update_date",
        "from resume_type"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cv_type_text", property="cvTypeText", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.VARCHAR)
    })
    List<ResumeType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_type
     *
     * @mbg.generated Sat Jun 08 14:05:49 PDT 2024
     */
    @Update({
        "update resume_type",
        "set cv_type_text = #{cvTypeText,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ResumeType record);
}